apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-staging

bases:
  - ../../base

namePrefix: staging-

patches:
  # Reducir réplicas en staging
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment

commonLabels:
  environment: staging
